### PR TITLE
pull from the beta branch

### PR DESCRIPTION
**Pull request by mo271**
With this I could install pypolymake

### CODE REVIEW

**Comment by videlec** [comment]
This is already mentioned in the README. Wasn't it clear enough?

**Comment by videlec** [comment]
If you are using the beta release of polymake you need to install the package from the
    beta branch with

        $ sage -i polymake-beta   # TO BE FIXED
        $ sage -pip install git+https://github.com/videlec/pypolymake@beta

**Comment by mo271** [comment]
I didn't read the README...

**Comment by videlec** [comment]
But you are providing a pull request that does modify it!?

**Comment by videlec** [comment]
Anyway I am happy to see that the beta version compiles on another computer!

**Pull request closed without merging**
